{
 "title": "General overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Usage in cores",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{}[$__rate_interval]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "CPU requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage in GB",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{})",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Memory requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "PVC total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes)",
     "legendFormat": "Total PVC size"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{}[$__rate_interval])) / sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Total PVC size"
    }
   ]
  },
  {
   "title": "Mem %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{}) / sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Total PVC size"
    }
   ]
  },
  {
   "title": "CPU Usage / Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ image!=\"\"}[$__rate_interval])) by (container, namespace)\n/ \nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (container, namespace)",
     "legendFormat": "{{namespace}} ({{container}})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (container, namespace) / sum(kube_pod_container_resource_requests{ resource=\"memory\"}) by (container,namespace)",
     "legendFormat": "{{namespace}} ({{container}})"
    }
   ]
  },
  {
   "title": "PVCs % Used",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n  (max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes)) \n  / \n  (max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_capacity_bytes)) \n  * 100\n",
     "legendFormat": "{{namespace}} - {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVCs % Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n  (max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes)) \n  / \n  (max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_capacity_bytes)) \n  * 100\n",
     "legendFormat": "{{namespace}} - {{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}