version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    groups:
      allgithubactions:
        patterns:
          - "*"
    commit-message:
      prefix: "⬆️(deps) "

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    groups:
      alldevcontainers:
        patterns:
          - "*"
    commit-message:
      prefix: "⬆️(deps) "

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    groups:
      allnpm:
        patterns:
          - "*"
    commit-message:
      prefix: "⬆️(deps) "
