helmDefaults:
  verify: true

missingFileHandler: "Error"

environments:
  default:
    values:  &values
      - "helmfile/environments/default/*.yaml*"

helmfiles:
  - path: "helmfile/apps/keycloak/helmfile-child.yaml"
    values: *values
  - path: "helmfile/apps/docs/helmfile-child.yaml"
    values: *values
  # - path: "helmfile/apps/element/helmfile-child.yaml"
  #   values: *values
  # - path: "helmfile/apps/ollama/helmfile-child.yaml"
  #   values: *values
