apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: postgresql-secrets
spec:
    secrets:
        - name: chat-postgres-sec-super
          stringData:
            username: ENC[AES256_GCM,data:cAO79R1MXISE,iv:mm2QyH8ltoG3IoPb9WX5keQRsaKDt+7n42r14FkXq9k=,tag:DYfLe9mAB53iuMeevVmJ1g==,type:str]
            password: ENC[AES256_GCM,data:L+tdUq+4fM8dmpDwnRRtaoi6L3xYMCkBTwdbDqL1Myk0HJ7AYRdz6dDOVmgH,iv:BpQzLPcTMrd4n0LO6uhB+84sxnqvLIwvMHRe5vmREX8=,tag:/kbA5PoebgezBlL9nsAWQQ==,type:str]
        - name: chat-postgres-sec
          stringData:
            username: ENC[AES256_GCM,data:SQPscA==,iv:54Vu4AaFav2FL0UKuZ+oCpC1Fe6UKWXCKC3xD6TFpfg=,tag:6CG54F3LzsnQbT26qRlGnQ==,type:str]
            password: ENC[AES256_GCM,data:KfBkzY10TfFnWfraummRns0p6JgsT4KzNz+Ppa0oVgp0oQn86Syf84aXnns=,iv:/Z+ffnBdXX4n5erPKGb5HJcWfJaSeUsjBbVwb82iKnw=,tag:sWIcK3wR+rRu8pVmPiZB2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmkdfjmsn9q0m245jasvay6he7kdm4ldmtear58t2hkzvmusfvvqrqffk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcnlNNWREZEhST1l6b2Fk
            NUNWbHBKdEZwTWRYUkVYb01MQ1NaMnFPUm04Cm5oZGMxdVJ4ekZCK21Wc2N0QXZV
            Wk9tOHRPYTVMaWJzVVNPMGJINVIycW8KLS0tIHlDcVM4MC9vQURMUzZrTkg1SFN5
            Z2dSOWZ1Y1ZGcStTb1Z1Uzlkd2szSGsKQBlZ6l6BVuFIkYQyd5K0e+u7uWQlbEHV
            0XNSbqCdgcf+P5GWTQxDuI5+shwDjspSRcrTclgsKzekW1E78XGjMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T13:40:09Z"
    mac: ENC[AES256_GCM,data:tkZ9AjB6Oa6sdBMxT7rbEqBBEZoDMYF2Wrvdqr3jylxPu04qkmmlk1yLbwdoOtIEdALD/+6ai/hRDDz1TNrzzfOfJi2NwL9HvajYuKLTyg2cfwappVGm84dOI3xOsz/lEehGou84VSbVgvKx+kga+0PsJnyYA7JoQlQbjRIocwU=,iv:TojxiW096C/ogt16HAO98YsxeM+RHRfLU309NIEGqY8=,tag:A5Abzcl8c/SqdgqC1c4vaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
