apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "element-web.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "element-web.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "element-web.fullname" . }}
    spec:
      containers:
        - name: element-web
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config.json
      volumes:
        - name: config
          configMap:
            name: {{ include "element-web.fullname" . }}-config
