{{- /*

SPDX-License-Identifier: EUPL-1.2
*/}}

{{- if eq .Values.cluster.routingMode "gateway-api" }}
{{- if .Values.ingressMediaPreview.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "common.names.fullname" . }}-media-preview
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: drive
  {{- include "common.httproute.annotations" . | nindent 2 }}
spec:
  parentRefs:
    {{- include "common.httproute.parentRef" .Values.cluster.gateway | nindent 4 }}
  hostnames:
    - {{ .Values.ingressMediaPreview.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.ingressMediaPreview.path | default "/media/preview" | quote }}
      filters:
        {{- include "common.httproute.secureMediaFilter" . | nindent 8 }}
      backendRefs:
        - name: {{ printf "%s-nginx" (include "common.names.fullname" .) }}
          port: 80
{{- end }}
{{- end }}
