apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
        - name: "dockerhub-icbr-robot-pull-secret"
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: "rcr.rijksapps.nl/dockerhub-icbr/library/redis:7.4.4"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
