{
 "title": "Nextcloud",
 "tags": [
  "prometheus",
  "nextcloud"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nextcloud_up, instance)"
   },
   {
    "name": "_nextcloud_version",
    "query": {
     "query": "query_result(group by (version) (nextcloud_system_info{instance=\"$instance\"}))"
    }
   },
   {
    "name": "_php_version",
    "query": {
     "query": "query_result(group by (version) (nextcloud_php_info{instance=\"$instance\"}))"
    }
   },
   {
    "name": "_database",
    "query": {
     "query": "query_result(label_join(group by (type, version) (nextcloud_database_info{instance=\"$instance\"}), \"info\", \" \", \"type\", \"version\"))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Users and Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Active Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_active_users_daily_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_users_total{instance=\"$instance\"})",
     "legendFormat": "total ({{instance}})"
    },
    {
     "expr": "sum by(instance) (nextcloud_active_users_total{instance=\"$instance\"})",
     "legendFormat": "active ({{instance}})"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_files_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Shares", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Shares by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (nextcloud_shares_total{instance=\"$instance\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Federated Shares",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(direction) (nextcloud_shares_federated_total{instance=\"$instance\"})",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Installed Apps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_apps_installed_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Updates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_apps_updates_available_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Version Info ($instance)",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "options": {
    "content": "<table>\n  <tbody>\n    <tr>\n      <th>Nextcloud Version</th>\n      <td>${_nextcloud_version}</td>\n    </tr>\n    <tr>\n      <th>PHP Version</th>\n      <td>${_php_version}</td>\n    </tr>\n    <tr>\n      <th>Database</th>\n      <td>${_database}</td>\n    </tr>\n  </tbody>\n</table>\n"
   }
  },
  {
   "title": "Disk Space Left",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_free_space_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Exporter Scrape Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 25 },
   "targets": [
    {
     "expr": "sum by (cause) (rate(nextcloud_scrape_errors_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Environment Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "PHP Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_php_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Databases (all instances)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type, version) (nextcloud_database_info)",
     "legendFormat": "{{type}} {{version}}"
    }
   ]
  },
  {
   "title": "Nextcloud Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_system_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_exporter_info)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}