{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}
{{- $secretEnvNames := splitList " " (include "docs.secretEnvNames" .) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.envVars }}
  {{- if and (has $key $secretEnvNames) (kindIs "string" $value) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.backend.migrateDbCredentials }}
  {{- if kindIs "string" .DB_PASSWORD }}
  MIGRATE_DB_PASSWORD: {{ .DB_PASSWORD | quote }}
  {{- end }}
  {{- end }}
  YPROVIDER_API_KEY: {{ .Values.yProvider.configuration.api.key | quote }}
  YPROVIDER_COLLABORATION_SERVER_SECRET: {{ .Values.yProvider.configuration.collaboration.serverSecret | quote }}
