apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-app
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.owner }}
  password: {{ .Values.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-superuser
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.adminPassword | quote }}
