{{- /*

SPDX-License-Identifier: EUPL-1.2
*/}}
{{- $secretEnvNames := splitList " " (include "bureaublad.secret.envNames" .) }}
{{- $envVars := merge (dict) (.Values.backend.envVars | default dict) (.Values.frontend.envVars | default dict) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: bureaublad
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := $envVars }}
  {{- if and (has $key $secretEnvNames) (not (kindIs "map" $value)) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
