{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: grist
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  GRIST_SESSION_SECRET: {{ .Values.sessionSecret | quote }}
  REDIS_URL: {{ printf "redis://default:%v@%v:%v" .Values.externalRedis.password .Values.externalRedis.host .Values.externalRedis.port | quote }}
  GRIST_DOCS_MINIO_ACCESS_KEY: {{ .Values.externalMinio.accessKey | quote }}
  GRIST_DOCS_MINIO_SECRET_KEY: {{ .Values.externalMinio.secretKey | quote }}
  TYPEORM_PASSWORD: {{ .Values.externalDatabase.password | quote }}
  {{- if .Values.licensekey }}
  GRIST_ACTIVATION: {{ .Values.licensekey | quote }}
  {{- end }}
  {{- if and .Values.ai.enabled .Values.ai.apiKey }}
  ASSISTANT_API_KEY: {{ .Values.ai.apiKey | quote }}
  {{- end }}
  {{- if .Values.auth.enabled }}
  GRIST_OIDC_IDP_CLIENT_SECRET: {{ .Values.auth.oidcIdpClientSecret | quote }}
  {{- end }}
