database:
    keycloak:
        host: ENC[AES256_GCM,data:e/gKfhtW63Sm9kHNs/51a7z7Sg==,iv:hw1XylyrXoTHvnD26GpHmZo/6PTqkPy3Y1vdbmQwoGU=,tag:rJdOZE8+lu7W2adlW3btJA==,type:str]
        user: ENC[AES256_GCM,data:3+5fAv0+ldc=,iv:wSnUfIH1QrZ7r5l+Wn33coK8ALbXOJ2EYrhGBYZFzLM=,tag:2s8/hDUxLqKJBp669WBO4Q==,type:str]
        password: ENC[AES256_GCM,data:FJC7TI/C3t0la0LInOGYTghNmaOx8nLJuVUaysqsPlXq1rvzfQgm3A==,iv:G4c9JAJ5FwV91xkMRLtTeM53D5nvMHx05g9xQPGCQB4=,tag:QNOWGEy4JOIJ6xRZsf1phg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdtakudhgztr4l7fdm2jcs9t0qpwdav7jk5x0wu735hs2xv0qywsmgcttl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWFVlSlhZREw1S0U5THE5
            bWNzem1BR1RtRGpoR3VuK3Z5VVRCaExKd2o0CnlKZVNybTdwL1ZtdCs0Z1h3M3hm
            Tnordldqb3Y0VlF2Nys2Z3dTa1AzM2MKLS0tIDN5K2QrUmM1QVFROVVJUFlBNnBj
            ckdyQ0IrVWFZVHNGU1BMSHh3dG80cUUKwqdx3zbYAO+odgXXgKtLpPSLhSJ2Zglk
            XROMFoqzGFprBXlKUpzLqfOFke5hfDR5GmLn5cGIclw0VAvgTAtF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T13:27:12Z"
    mac: ENC[AES256_GCM,data:zIfp/mIQhG55uv3Q94J5TdBmW8sC4tyeCpJewJ+HpFh94C+b5Wh7LKBOpAXZWU/PFEHF8O3yRl5UbCeZc3lQzLoAud60dkfyPBqTNbl1T7vd168i2aUD+8Ajrd39kp9l+b/zRzKe4V9zyJmewTPiwN0hRLNfpLLFfvPtLXrKOR8=,iv:LvS9XC3T17KU4ZDWaGu3yQZjyZBgRQ6mGEl+c9L9oTQ=,tag:qlPyWnqX2RXTGI1EuSp0aw==,type:str]
    pgp: []
    encrypted_regex: ^*$
    version: 3.8.1
