{{- /*
SPDX-License-Identifier: EUPL-1.2
*/}}

{{- if eq .Values.cluster.routingMode "gateway-api" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ollama.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "ollama.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ollama
  {{- include "common.httproute.annotations" . | nindent 2 }}
spec:
  parentRefs:
    {{- include "common.httproute.parentRef" .Values.cluster.gateway | nindent 4 }}
  hostnames:
    - {{ (first .Values.ingress.hosts).host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        {{- include "common.httproute.hstsFilter" . | nindent 8 }}
      backendRefs:
        - name: {{ include "ollama.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
