apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "synapse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synapse.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "synapse.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.server.name }}
              containerPort: {{ .Values.service.server.port }}
              protocol: TCP
            - name: {{ .Values.service.replication.name }}
              containerPort: {{ .Values.service.replication.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SYNAPSE_CONFIG_DIR
              value: {{ .Values.synapse.config.synapseConfigDir }}
            - name: SYNAPSE_CONFIG_PATH
              value: {{ .Values.synapse.config.synapseConfigPath }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .Values.synapse.signingKey.localConfigLocation }}
            - name: synapse-signing-key
              mountPath: /secrets/
              readOnly: true
            {{- end }}
            - name: synapse-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "synapse.fullname" . }}
        {{- if .Values.synapse.signingKey.localConfigLocation }}
        - name: synapse-signing-key
          secret:
            secretName: synapse-signing-key
        {{- end }}
        - name: synapse-config
          configMap:
            name: {{ include "synapse.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
