apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "element-web.fullname" . }}-config
data:
  config.json: |
    {
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://{{ .Values.global.matrixDomain | default "example.com" }}",
            "server_name": "{{ .Values.global.domain | default "example.com" }}"
        }
    },
    "features": {
        "feature_video_rooms": true,
        "feature_pinning": true,
        "feature_custom_themes": true,
        "feature_element_call_video_rooms": true,
        "feature_group_calls": true,
        "feature_html_topic": true,
        "feature_ask_to_join": true
    },
    "default_federate": true,
    "default_country_code": "NL",
    "room_directory": {
        "servers": [
            "{{ .Values.hostname.element | default "element-web" }}.{{ .Values.global.domain | default "example.com" }}",
            "matrix.org"
        ]
    },
    "setting_defaults": {
        "breadcrumbs": true
    },
    "default_theme": "light",
    "brand": "{{ .Values.global.domain | default "example.com" }} chat",
    "permalink_prefix": "https://{{ .Values.hostname.element | default "element-web" }}.{{ .Values.global.domain | default "example.com" }}",
    "disable_guests": true,
    "force_verification": false,
    "logout_redirect_url": "https://{{ .Values.hostname.element | default "element-web" }}.{{ .Values.global.domain | default "example.com" }}",
    "sso_redirect_options": {
        "immediate": true
    },
    "disable_custom_urls": true,
    "disable_3pid_login": true,
    "default_widget_container_height": 280,
    "show_labs_settings": true,
    "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx" # We need to make research about it and check if we really need it.
}
