authentication:
  # OIDC (OpenIDConnect) options will only be used if `application.keycloak.enabled` is false
  # the purpose of this setting is to replace keycloak with an existing oidc provider
  oidc:
    issuer: "https://example.com/realms/master"
    authorization_endpoint: "https://example.com/realms/master/protocol/openid-connect/auth"
    token_endpoint: "https://example.com/realms/master/protocol/openid-connect/token"
    introspection_endpoint: "https://example.com/realms/master/protocol/openid-connect/token/introspect"
    userinfo_endpoint: "https://example.com/realms/master/protocol/openid-connect/userinfo"
    end_session_endpoint: "https://example.com/realms/master/protocol/openid-connect/logout"
    jwks_uri: "https://example.com/realms/master/protocol/openid-connect/certs"




