---
### This file contains all the kubernetes cluster-wide settings, please edit it to match your environment.
cluster:
  networking:
    domain: cluster.local
    cidr:
      - "10.0.0.0/8"

  container:
    engine: cri-o

  operator:
    prometheus: # https://prometheus-operator.dev/
      enabled: true
    cert-manager:
      enabled: true
    cloudnativepg: # https://cloudnative-pg.io/
      enabled: true
    #todo: add other ingressess

  ingress:
    type: nginx
    ingressClassName: ""

  storageClassNames:
    RWX: ""
    RWO: ""


  certificate:
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer



