---
cluster:
  # Based on the available Implementations of your cluster, choose the type of Service.
  # Choose out of "ClusterIP", "NodePort" or "LoadBalancer.
  service:
    type: "ClusterIP"

  networking:
    domain: cluster.local
    cidr:
      - "10.0.0.0/8"

  container:
    engine: cri-o

  sandbox:
    gvisor:
      enabled: false

  operator:
    prometheus:
      enabled: true
    cert-manager:
      enabled: true
    external-dns:
      enabled: true
    ingress-nginx:
      enabled: true
