---
cluster:
  networking:
    domain: cluster.local
    cidr:
      - "10.0.0.0/8"
  container:
    engine: cri-o


  operator:
    prometheus:
      enabled: true
    cert-manager:
      enabled: true
    external-dns:
      enabled: true
    ingress-nginx:
      enabled: true


