{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.metrics.enabled (not .Values.metrics.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-metrics-token" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: metrics
  annotations:
    helm.sh/resource-policy: keep
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{ .Values.metrics.auth.secretKey }}: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-metrics-token" (include "common.names.fullname" .)) "key" .Values.metrics.auth.secretKey "providedValues" (list "metrics.auth.token") "length" 64 "strong" false "context" $) }}
{{- end }}
