{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and (not .Values.externalMinio.existingSecret) .Values.externalMinio.username .Values.externalMinio.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externalminio" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: nextcloud
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "nextcloud.minio.secretUsernameKey" . }}: {{ .Values.externalMinio.username | b64enc | quote }}
  {{ include "nextcloud.minio.secretPasswordKey" . }}: {{ .Values.externalMinio.password | b64enc | quote }}
{{- end -}}
