{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if (include "nextcloud.createSecret" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: nextcloud
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.auth.existingSecret }}
  nextcloud-username: {{ include "nextcloud.username" . | b64enc | quote }}
  nextcloud-password: {{ include "nextcloud.password" . | b64enc | quote }}
  {{- end }}
  {{- if and .Values.mail.enabled (not .Values.mail.smtp.auth.existingSecret) }}
  smtp-username: {{ .Values.mail.smtp.auth.username | b64enc | quote }}
  smtp-password: {{ .Values.mail.smtp.auth.password | b64enc | quote }}
  {{- end }}
{{- end -}}
