name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check if changelog is updated
        run: |
          if ! git diff --name-only origin/main | grep -q '^CHANGELOG.md$'; then
            echo "Error: CHANGELOG.md must be updated for PRs."
            exit 1
          fi

  lint-commit-messages:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Show logs
        run: git log

      - name: Install gitlint
        run: pip install requests gitlint

      - name: Lint commit messages added to main
        run: gitlint --commits origin/${{ github.event.pull_request.base.ref }}..HEAD

  render-helmfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install helm
        run: |
          wget -O - https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install helmfile
        run: |
          cd /tmp/
          wget https://github.com/helmfile/helmfile/releases/download/v1.1.2/helmfile_1.1.2_linux_amd64.tar.gz
          tar -xzf helmfile_1.1.2_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/helmfile

      - name: Initilize helmfile dependecies
        run: |
          helmfile init --force

      - name: Render helmfile for all environments
        run: |
          helmfile -e production template --output-dir=/tmp/manifest/production
          helmfile -e demo template --output-dir=/tmp/manifest/demo
          helmfile template --output-dir=/tmp/manifest/default
        env:
          MIJNBUREAU_MASTER_PASSWORD: ${{ secrets.MIJNBUREAU_MASTER_PASSWORD || 'dependabot' }}
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY || 'dependabot'  }}

      - name: Prepare file Upload
        run: |
          cd /tmp/manifest/
          find . -type f -name "*.yaml.gotmpl" | while read file; do
            mv "$file" "${file%.gotmpl}"
          done

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: /tmp/manifest/
          if-no-files-found: error
          retention-days: 3

  verify-policies:
    runs-on: ubuntu-latest
    needs: [render-helmfile]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: rendered-manifests
          path: /tmp/manifest

      - name: Install conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.61.2/conftest_0.61.2_linux_amd64.deb
          sudo dpkg -i conftest_0.61.2_linux_amd64.deb

      - name: Run conftest against rendered manifests
        run: |
          conftest test /tmp/manifest/production --output=github
          conftest test /tmp/manifest/demo --output=github
          conftest test /tmp/manifest/default --output=github

  check-format-rules:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install prettier
        run: npm install -g prettier

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run formatters
        run: ./scripts/format.sh

      - name: Check for changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Error: Detected uncommitted changes after formatting. Please run the formatter locally and commit the results."
            git status
            git diff
            exit 1
          fi

      - name: run pre-commit
        run: pre-commit run --all-files

  check-kubernetes-conformance:
    runs-on: ubuntu-latest
    needs: [render-helmfile]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: rendered-manifests
          path: /tmp/manifest

      - name: Install kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/download/v0.7.0/kubeconform-linux-amd64.tar.gz -O /tmp/kubeconform.tar.gz
          tar -xzf /tmp/kubeconform.tar.gz -C /tmp/
          mv /tmp/kubeconform /usr/local/bin/kubeconform
          chmod +x /usr/local/bin/kubeconform

      - name: Run kubeconform against rendered manifests
        run: |
          kubeconform -strict -summary /tmp/manifest/production/
          kubeconform -strict -summary /tmp/manifest/demo/
          kubeconform -strict -summary /tmp/manifest/default/

  notify-mattermost:
    runs-on: ubuntu-latest
    needs:
      [
        check-changelog,
        lint-commit-messages,
        check-format-rules,
        render-helmfile,
        verify-policies,
        check-kubernetes-conformance,
      ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - uses: mattermost/action-mattermost-notify@master
        if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK }}
          MATTERMOST_CHANNEL: github-actions
          TEXT: |
            ## 🚨 CI Pipeline Failed

            **Repository:** `${{ github.repository }}`
            **Branch/Tag:** `${{ github.head_ref }}`
            **Triggered by:** @${{ github.actor }}
            **Event:** ${{ github.event_name }}

            ### Failed Jobs:
            ${{ needs.lint-commit-messages.result == 'failure' && '❌ Commit Message Linting' || '' }}
            ${{ needs.check-format-rules.result == 'failure' && '❌ Format & Pre-commit Checks' || '' }}

            ### Quick Actions:
            - 🔍 [View Pipeline Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - 📝 [View Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            ${{ github.event_name == 'pull_request' && format('- 🔄 [View Pull Request]({0}/{1}/pull/{2})', github.server_url, github.repository, github.event.number) || '' }}
