name: Test docs deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  test-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          with:
            node-version-file: ".nvmrc"
            cache: npm
            cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
